# This file contains non-secret configuration for all RASS services.
# It should be committed to version control.

# --- Global Settings ---
OPENSEARCH_HOST: "opensearch"
OPENSEARCH_PORT: 9200
OPENSEARCH_INDEX_NAME: "knowledge_base"

# --- Redis Configuration ---
REDIS_HOST: "redis"
REDIS_PORT: 6379
REDIS_DB: 0

# --- Provider Choices ---
# Can be "openai" or "gemini"
EMBEDDING_PROVIDER: "gemini"
LLM_PROVIDER: "gemini"
SEARCH_TERM_EMBEDDING_PROVIDER: "gemini"

# --- Model Names ---
# Embedding Models
OPENAI_EMBED_MODEL_NAME: "text-embedding-3-large"
GEMINI_EMBED_MODEL_NAME: "text-embedding-004"
# LLM (Generator) Models
OPENAI_MODEL_NAME: "gpt-4.1-nano"
GEMINI_MODEL_NAME: "gemini-2.0-flash"
# Reranker Model
RERANKER_MODEL_NAME: "cross-encoder/ms-marco-MiniLM-L6-v2"

# --- Service Ports ---
EMBEDDING_SERVICE_PORT: 8001
RASS_ENGINE_PORT: 8000
MCP_SERVER_PORT: 8080
RERANKER_PORT: 8008

# --- RAG Parameters ---
# For Small-to-Big Retrieval
PARENT_CHUNK_SIZE: 2000
PARENT_CHUNK_OVERLAP: 500
CHILD_CHUNK_SIZE: 200
CHILD_CHUNK_OVERLAP: 100
# Initial candidate pool size for reranking
DEFAULT_K_OPENSEARCH_HITS: 112
# Vector dimension for OpenSearch index
EMBED_DIM: 768

# Search score thresholds
OPENSEARCH_SCORE_THRESHOLD: 0.1

search:
  DEFAULT_TOP_K: 50
